# Generated by Django 5.2.5 on 2025-08-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='interests',
            new_name='preferences',
        ),
    ]
