# Generated by Django 5.2.5 on 2025-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_interests_customuser_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
