# Generated by Django 5.2.5 on 2025-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_trial_end_date'),
        ('events', '0002_event_attendees_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_events',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='events.event'),
        ),
    ]
