# Generated by Django 5.2.5 on 2025-08-28 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalize', '0004_alter_interest_options_remove_itinerary_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event_images/')),
                ('category', models.CharField(choices=[('MUSIC', 'Music'), ('TECHNOLOGY', 'Technology'), ('FOOD_DRINK', 'Food & Drink'), ('OUTDOOR', 'Outdoor'), ('SPORTS', 'Sports'), ('ART_CULTURE', 'Art & Culture'), ('EDUCATION', 'Education'), ('HEALTH_WELLNESS', 'Health & Wellness')], max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_phone', models.CharField(max_length=20)),
                ('organizer_website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='personalize.interest')),
            ],
        ),
    ]
