# Generated by Django 5.2.5 on 2025-08-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0002_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='budget',
            field=models.CharField(blank=True, choices=[('50-100', '$50/100 day'), ('100-200', '$100/200 day'), ('200-300', '$200/300 day'), ('300-500+', '$300/500+ day')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='duration',
            field=models.CharField(blank=True, choices=[('3_DAYS', '3 days'), ('5_DAYS', '5 days'), ('1_WEEK', '1 week'), ('10_DAYS', '10 days'), ('2_WEEKS', '2 weeks')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('SOLO', 'Solo'), ('COUPLE', 'Couple'), ('FAMILY', 'Family'), ('GROUP', 'Group')], max_length=10, null=True),
        ),
    ]
