# Generated by Django 5.2.5 on 2025-08-27 10:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0003_itinerary_budget_itinerary_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={},
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='title',
        ),
        migrations.AddField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 27, 10, 27, 14, 405286, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='budget',
            field=models.CharField(choices=[('50-100', '$50/100 day'), ('100-200', '$100/200 day'), ('200-300', '$200/300 day'), ('300-500+', '$300/500+ day')], default='50-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(default='Default Destination', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='duration',
            field=models.CharField(choices=[('3_DAYS', '3 days'), ('5_DAYS', '5 days'), ('1_WEEK', '1 week'), ('10_DAYS', '10 days'), ('2_WEEKS', '2 weeks')], default='3_DAYS', max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='trip_type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('COUPLE', 'Couple'), ('FAMILY', 'Family'), ('GROUP', 'Group')], default='SOLO', max_length=10),
        ),
    ]
